"""
Shared data: COMMON_TICKERS and LANGUAGE strings
"""

# ─── COMMON TICKERS ───────────────────────────────────────────────
# Format: (display_name, ticker, full_name)
COMMON_TICKERS = [
    # === 美股前50大市值 ===
    ("蘋果", "AAPL", "Apple Inc."),
    ("微軟", "MSFT", "Microsoft Corp."),
    ("Alphabet", "GOOGL", "Alphabet Inc."),
    ("亞馬遜", "AMZN", "Amazon.com Inc."),
    ("輝達", "NVDA", "NVIDIA Corp."),
    ("Meta", "META", "Meta Platforms"),
    ("特斯拉", "TSLA", "Tesla Inc."),
    ("伯克夏", "BRK-B", "Berkshire Hathaway"),
    ("禮來", "LLY", "Eli Lilly"),
    ("博通", "AVGO", "Broadcom Inc."),
    ("摩根大通", "JPM", "JPMorgan Chase"),
    ("威士", "V", "Visa Inc."),
    ("強生", "JNJ", "Johnson & Johnson"),
    ("萬事達", "MA", "Mastercard"),
    ("家樂福", "WMT", "Walmart Inc."),
    ("雪佛龍", "XOM", "Exxon Mobil"),
    ("寶僑", "PG", "Procter & Gamble"),
    ("輝瑞", "PFE", "Pfizer Inc."),
    ("可口可樂", "KO", "Coca-Cola Co."),
    ("百事", "PEP", "PepsiCo"),
    ("達美樂", "COST", "Costco Wholesale"),
    ("Adobe", "ADBE", "Adobe Inc."),
    ("賽富時", "CRM", "Salesforce Inc."),
    ("AMD", "AMD", "Advanced Micro Devices"),
    ("Netflix", "NFLX", "Netflix Inc."),
    ("Intuit", "INTU", "Intuit Inc."),
    ("德州儀器", "TXN", "Texas Instruments"),
    ("Mastercard", "MA", "Mastercard Inc."),
    ("Visa", "V", "Visa Inc."),
    ("Cisco", "CSCO", "Cisco Systems"),
    ("Accenture", "ACN", "Accenture plc"),
    ("安進", "AMGN", "Amgen Inc."),
    ("PayPal", "PYPL", "PayPal Holdings"),
    ("高通", "QCOM", "Qualcomm Inc."),
    ("IBM", "IBM", "IBM Corp."),
    (" walmart", "WMT", "Walmart Inc."),
    ("Shopify", "SHOP", "Shopify Inc."),
    ("Block", "SQ", "Block Inc."),
    ("Coinbase", "COIN", "Coinbase Global"),
    ("Uber", "UBER", "Uber Technologies"),
    ("Pinterest", "PINS", "Pinterest Inc."),
    ("Spotify", "SPOT", "Spotify Technology"),
    ("Airbnb", "ABNB", "Airbnb Inc."),
    ("Robinhood", "HOOD", "Robinhood Markets"),
    ("Square", "SQ", "Block Inc."),
    ("Spotify", "SPOT", "Spotify AB"),
    ("Salesforce", "CRM", "Salesforce Inc."),
    ("ServiceNow", "NOW", "ServiceNow Inc."),
    ("CrowdStrike", "CRWD", "CrowdStrike Holdings"),
    ("Palo Alto Networks", "PANW", "Palo Alto Networks"),
    
    # === 台股 ===
    ("台積電", "2330.TW", "Taiwan Semiconductor"),
    ("鴻海", "2317.TW", "Foxconn/Hon Hai"),
    ("聯發科", "2454.TW", "MediaTek"),
    ("中華電信", "2412.TW", "Chunghwa Telecom"),
    ("國泰金", "2882.TW", "Cathay Financial"),
    ("富邦金", "2881.TW", "Fubon Financial"),
    ("玉山金", "2884.TW", "ESUN Financial"),
    ("元大金", "2885.TW", "Yuanta Financial"),
    ("長榮航", "2610.TW", "EVA Air"),
    ("兆豐金", "2886.TW", "Mega Financial"),
    ("富邦媒", "9910.TW", "PChome Online"),
    ("智易", "3255.TW", "Sigmatek"),
    ("創意", "3443.TW", "MediaTek Inc."),
    ("康寧", "3003.TW", "Coretronic"),
    ("友訊", "2395.TW", "D-Link"),
    ("緯創", "3231.TW", "Wistron"),
    ("和碩", "4938.TW", "Quanta Computer"),
    ("廣達", "2382.TW", "Quanta Computer"),
    ("仁宝", "2324.TW", "Compal Electronics"),
    ("微星", "2377.TW", "MSI"),
    ("華碩", "2357.TW", "ASUSTeK"),
    ("凌陽", "2488.TW", "Sunplus Technology"),
    ("瑞昱", "2379.TW", "Realtek Semiconductor"),
    ("聯詠", "3443.TW", "Novatek Microelectronics"),
    ("奇美電", "2411.TW", "Chimei Innolux"),
    ("友達", "2409.TW", "AU Optronics"),
    ("群創", "3481.TW", "Innolux Corp"),
    ("鴻超聚", "3068.TW", "Fugoo Technology"),
    ("康舒", "3533.TW", "Acpack"),
    
    # === 中國/A股/港股 ===
    ("騰訊", "0700.HK", "Tencent Holdings"),
    ("阿里巴巴", "9988.HK", "Alibaba Group"),
    ("美團", "3690.HK", "Meituan"),
    ("小米", "1810.HK", "Xiaomi Corp"),
    ("比亞迪", "1211.HK", "BYD Company"),
    ("茅台", "600519.SS", "Kweichow Moutai"),
    ("平安", "601318.SS", "Ping An Insurance"),
    ("網易", "9999.HK", "NetEase Inc"),
    ("京東", "9618.HK", "JD.com"),
    ("拼多多", "PDD", "PDD Holdings"),
    ("百度", "BIDU", "Baidu Inc"),
    ("滴滴", "DD", "DiDi Global"),
    ("中芯國際", "0981.HK", "SMIC"),
    ("吉利汽車", "0175.HK", "Geely Auto"),
    ("海康威視", "002415.SZ", "Hikvision"),
    ("萬科", "000002.SZ", "Vanke Co"),
    ("招商銀行", "600036.SS", "China Merchants Bank"),
    ("中信銀行", "601998.SS", "CITIC Bank"),
    ("工商銀行", "601398.SS", "ICBC"),
    ("建設銀行", "601939.SS", "China Construction Bank"),
    
    # === 韓國/日本/印度 ===
    ("三星電子", "005930.KS", "Samsung Electronics"),
    ("SK海力士", "000660.KS", "SK Hynix"),
    ("LG化學", "051910.KS", "LG Chem"),
    ("現代汽車", "005380.KS", "Hyundai Motor"),
    ("索尼", "6758.T", "Sony Group"),
    ("任天堂", "7974.T", "Nintendo Co"),
    ("軟銀", "9984.T", "SoftBank Group"),
    ("丰田", "7203.T", "Toyota Motor"),
    ("夏普", "6752.T", "Sharp Corp"),
    ("Infosys", "INFY", "Infosys Ltd"),
    ("Reliance", "RELIANCE.NS", "Reliance Industries"),
    ("TCS", "TCS.NS", "Tata Consultancy Services"),
    
    # === 加密貨幣 ===
    ("比特幣", "BTC-USD", "Bitcoin USD"),
    ("以太坊", "ETH-USD", "Ethereum USD"),
    ("BNB", "BNB-USD", "Binance Coin"),
    ("Solana", "SOL-USD", "Solana USD"),
    ("XRP", "XRP-USD", "Ripple USD"),
    ("Cardano", "ADA-USD", "Cardano USD"),
    ("Dogecoin", "DOGE-USD", "Dogecoin USD"),
    ("Avalanche", "AVAX-USD", "Avalanche USD"),
    ("Polkadot", "DOT-USD", "Polkadot USD"),
    ("Chainlink", "LINK-USD", "Chainlink USD"),
    
    # === 期貨/原物料 ===
    ("黃金期貨", "GC=F", "Gold Futures"),
    ("白銀期貨", "SI=F", "Silver Futures"),
    ("原油期貨", "CL=F", "Crude Oil Futures"),
    ("布蘭特原油", "BZ=F", "Brent Crude Oil"),
    ("天然氣", "NG=F", "Natural Gas"),
    ("銅期貨", "HG=F", "Copper Futures"),
    ("小麥期貨", "W=F", "Wheat Futures"),
    ("玉米期貨", "C=F", "Corn Futures"),
    ("黃豆期貨", "S=F", "Soybean Futures"),
    ("咖啡期貨", "KC=F", "Coffee Futures"),
    ("糖期貨", "SB=F", "Sugar Futures"),
    ("棉花期貨", "CT=F", "Cotton Futures"),
    
    # === ETF ===
    ("SPY", "SPY", "SPDR S&P 500 ETF"),
    ("QQQ", "QQQ", "Invesco QQQ Trust"),
    ("IWM", "IWM", "iShares Russell 2000"),
    ("VTI", "VTI", "Vanguard Total Stock Market"),
    ("VOO", "VOO", "Vanguard S&P 500"),
    ("GLD", "GLD", "SPDR Gold Shares"),
    ("SLV", "SLV", "iShares Silver Trust"),
    ("USO", "USO", "United States Oil Fund"),
    ("DBA", "DBA", "Invesco DB Agriculture"),
    ("XLF", "XLF", "Financial Select Sector SPDR"),
    ("XLK", "XLK", "Technology Select Sector SPDR"),
    ("XLE", "XLE", "Energy Select Sector SPDR"),
    ("VEA", "VEA", "Vanguard FTSE Developed Markets"),
    ("VWO", "VWO", "Vanguard FTSE Emerging Markets"),
    ("EEM", "EEM", "iShares MSCI Emerging Markets"),
    ("TLT", "TLT", "iShares 20+ Year Treasury Bond"),
    ("HYG", "HYG", "iShares High Yield Corporate Bond"),
    ("LQD", "LQD", "iShares Investment Grade Corporate Bond"),
    ("XLU", "XLU", "Utilities Select Sector SPDR"),
    ("XLV", "XLV", "Health Care Select Sector SPDR"),
    
    # === 指數 ===
    ("S&P 500", "^GSPC", "S&P 500 Index"),
    ("NASDAQ", "^IXIC", "NASDAQ Composite"),
    ("道瓊", "^DJI", "Dow Jones Industrial Average"),
    ("FTSE 100", "^FTSE", "FTSE 100 Index"),
    ("DAX", "^GDAXI", "DAX Performance Index"),
    ("日經225", "^N225", "Nikkei 225"),
    ("上證綜指", "000001.SS", "Shanghai Composite"),
    ("恆生指數", "^HSI", "Hang Seng Index"),
    ("KOSPI", "^KS11", "Korea Composite Stock Price"),
    ("ASX 200", "^AXJO", "S&P/ASX 200"),
    ("台灣加權", "^TWII", "Taiwan Weighted Index"),
    ("NSE Nifty", "^NSEI", "Nifty 50 Index"),
    ("BSE Sensex", "^BSESN", "BSE Sensex"),
    ("Euro Stoxx 50", "^STOXX50E", "Euro Stoxx 50"),
    ("澳洲200", "^AXJO", "ASX 200"),
    ("土耳其", "^TUFE.XS", "BIST 100"),
    
    # === 匯率 ===
    ("美元/台幣", "USDTWD=X", "USD/TWD"),
    ("美元/人民幣", "USDCNY=X", "USD/CNY"),
    ("美元/港幣", "USDHKD=X", "USD/HKD"),
    ("美元/韓元", "USDKRW=X", "USD/KRW"),
    ("歐元/美元", "EURUSD=X", "EUR/USD"),
    ("美元/日元", "USDJPY=X", "USD/JPY"),
    ("美元/英鎊", "GBPUSD=X", "GBP/USD"),
    ("澳元/美元", "AUDUSD=X", "AUD/USD"),
    ("紐元/美元", "NZDUSD=X", "NZD/USD"),
    ("瑞士法郎/美元", "CHFUSD=X", "CHF/USD"),
    ("加元/美元", "CADUSD=X", "CAD/USD"),
    ("新加坡/美元", "SGDUSD=X", "SGD/USD"),
]

# ─── DEFAULT WATCHLISTS ─────────────────────────────────────────
DEFAULT_WATCHLISTS = {
    "全球主要指數": [
        ("SPX", "^GSPC", "S&P 500"),
        ("NASDAQ", "^IXIC", "NASDAQ Composite"),
        ("DOW", "^DJI", "Dow Jones"),
        ("FTSE100", "^FTSE", "UK FTSE 100"),
        ("DAX", "^GDAXI", "Germany DAX"),
        ("日經225", "^N225", "Nikkei 225"),
        ("上證綜指", "000001.SS", "SSE Composite"),
        ("恆生指數", "^HSI", "Hang Seng"),
        ("KOSPI", "^KS11", "Korea KOSPI"),
        ("ASX200", "^AXJO", "Australia ASX 200"),
    ],
    "科技股 ETF": [
        ("QQQ", "QQQ", "Invesco QQQ Trust"),
        ("VGT", "VGT", "Vanguard Info Tech"),
    ],
}
