"""
LANGUAGE TRANSLATIONS
"""

LANG = {
    "app_title": {
        "zh-TW": "yfinance 自選股管理器",
        "zh-CN": "yfinance 自选股管理器",
        "en": "yfinance Watchlist Manager",
        "ja": "yfinance ウォッチリスト マネージャー",
        "ko": "yfinance 관심종목 관리자",
        "es": "yfinance Gestor de Lista",
    },
    "status_ready": {
        "zh-TW": "就緒 — 請點選 Watchlist 並按更新價格",
        "zh-CN": "就绪 — 请点选 Watchlist 并按更新价格",
        "en": "Ready — select a Watchlist and press Refresh",
        "ja": "準備完了 — Watchlist を選択して更新を押してください",
        "ko": "준비 — 관심종목을 선택하고 새로고침을 누르세요",
        "es": "Listo — selecciona una Watchlist y pulsa Actualizar",
    },
    "btn_new_wl": {
        "zh-TW": "＋ 新增 Watchlist",
        "zh-CN": "＋ 新增 Watchlist",
        "en": "+ New Watchlist",
        "ja": "＋ 新しい Watchlist",
        "ko": "＋ 새 Watchlist",
        "es": "+ Nueva Watchlist",
    },
    "btn_del_wl": {
        "zh-TW": "－ 刪除 Watchlist",
        "zh-CN": "－ 删除 Watchlist",
        "en": "- Del Watchlist",
        "ja": "－ Watchlist 削除",
        "ko": "－ Watchlist 삭제",
        "es": "- Eliminar Watchlist",
    },
    "btn_add_item": {
        "zh-TW": "＋ 加入商品",
        "zh-CN": "＋ 加入商品",
        "en": "+ Add Item",
        "ja": "＋ 商品追加",
        "ko": "＋ 종목 추가",
        "es": "+ Agregar",
    },
    "btn_del_item": {
        "zh-TW": "－ 移除商品",
        "zh-CN": "－ 移除商品",
        "en": "- Remove",
        "ja": "－ 商品削除",
        "ko": "－ 종목 제거",
        "es": "- Eliminar",
    },
    "btn_refresh_cur": {
        "zh-TW": "更新目前 WL",
        "zh-CN": "更新目前 WL",
        "en": "Refresh WL",
        "ja": "WL 更新",
        "ko": "WL 새로고침",
        "es": "Actualizar WL",
    },
    "btn_refresh_all": {
        "zh-TW": "更新所有價格",
        "zh-CN": "更新所有价格",
        "en": "Refresh All",
        "ja": "全て更新",
        "ko": "전체 새로고침",
        "es": "Actualizar Todo",
    },
    "col_name": {
        "zh-TW": "名稱",
        "zh-CN": "名称",
        "en": "Name",
        "ja": "名称",
        "ko": "이름",
        "es": "Nombre",
    },
    "col_ticker": {
        "zh-TW": "Ticker",
        "zh-CN": "Ticker",
        "en": "Ticker",
        "ja": "ティッカー",
        "ko": "티커",
        "es": "Ticker",
    },
    "col_price": {
        "zh-TW": "現價",
        "zh-CN": "现价",
        "en": "Price",
        "ja": "現在値",
        "ko": "현재가",
        "es": "Precio",
    },
    "col_change": {
        "zh-TW": "漲跌",
        "zh-CN": "涨跌",
        "en": "Change",
        "ja": "前日比",
        "ko": "등락",
        "es": "Cambio",
    },
    "col_pct": {
        "zh-TW": "漲跌幅",
        "zh-CN": "涨跌幅",
        "en": "% Chg",
        "ja": "騰落率",
        "ko": "등락률",
        "es": "% Var",
    },
    "col_vol": {
        "zh-TW": "成交量",
        "zh-CN": "成交量",
        "en": "Volume",
        "ja": "出来高",
        "ko": "거래량",
        "es": "Volumen",
    },
    "col_count": {
        "zh-TW": "#",
        "zh-CN": "#",
        "en": "#",
        "ja": "#",
        "ko": "#",
        "es": "#",
    },
    "frame_watchlists": {
        "zh-TW": "  Watchlists  ",
        "zh-CN": "  Watchlists  ",
        "en": "  Watchlists  ",
        "ja": "  ウォッチリスト  ",
        "ko": "   관심종목  ",
        "es": "   Listas  ",
    },
    "frame_prices": {
        "zh-TW": "  商品價格  ",
        "zh-CN": "  商品价格  ",
        "en": "  Prices  ",
        "ja": "  価格一覧  ",
        "ko": "   가격  ",
        "es": "   Precios  ",
    },
    "frame_search": {
        "zh-TW": "  加入商品 - 輸入 ticker 或名稱即搜尋（雙擊結果直接加入）  ",
        "zh-CN": "  加入商品 - 输入 ticker 或名称即搜寻（双击结果直接加入）  ",
        "en": "  Add Item - type ticker or name (double-click result to add)  ",
        "ja": "  商品追加 - ティッカーまたは名称を入力（ダブルクリックで追加）  ",
        "ko": "  종목추가 - 티커 또는 이름 입력 (더블클릭으로 추가)  ",
        "es": "  Agregar - escribe ticker o nombre (doble clic para agregar)  ",
    },
    "lbl_search": {
        "zh-TW": "搜尋 / Ticker：",
        "zh-CN": "搜寻 / Ticker：",
        "en": "Search / Ticker:",
        "ja": "検索 / ティッカー：",
        "ko": "검색 / 티커:",
        "es": "Buscar / Ticker:",
    },
    "lbl_result": {
        "zh-TW": "搜尋結果（雙擊加入目前 Watchlist）：",
        "zh-CN": "搜寻结果（双击加入目前 Watchlist）：",
        "en": "Results (double-click to add):",
        "ja": "検索結果（ダブルクリックで追加）：",
        "ko": "검색결과 (더블클릭으로 추가):",
        "es": "Resultados (doble clic para agregar):",
    },
    "lbl_custom_name": {
        "zh-TW": "顯示名稱(選填)：",
        "zh-CN": "显示名称(选填)：",
        "en": "Label (optional):",
        "ja": "表示名（任意）：",
        "ko": "표시명 (선택사항):",
        "es": "Etiqueta (opcional):",
    },
    "btn_add_selected": {
        "zh-TW": "＋ 加入所選",
        "zh-CN": "＋ 加入所选",
        "en": "+ Add Selected",
        "ja": "＋ 選択を追加",
        "ko": "＋ 선택 추가",
        "es": "+ Agregar Seleccionado",
    },
    "btn_direct_input": {
        "zh-TW": "直接輸入 Ticker",
        "zh-CN": "直接输入 Ticker",
        "en": "Direct Input",
        "ja": "ティッカー直接入力",
        "ko": "티커 직접 입력",
        "es": "Entrada Directa",
    },
    "dlg_add_title": {
        "zh-TW": "新增商品",
        "zh-CN": "新增商品",
        "en": "Add Item",
        "ja": "商品追加",
        "ko": "종목 추가",
        "es": "Agregar",
    },
    "dlg_ticker_hint": {
        "zh-TW": "Ticker（例 AAPL、BTC-USD、005930.KS、EURUSD=X）：",
        "zh-CN": "Ticker（例 AAPL、BTC-USD、005930.KS、EURUSD=X）：",
        "en": "Ticker (e.g. AAPL, BTC-USD):",
        "ja": "ティッカー（例 AAPL、BTC-USD）：",
        "ko": "티커 (예 AAPL, BTC-USD):",
        "es": "Ticker (ej. AAPL, BTC-USD):",
    },
    "dlg_label_hint": {
        "zh-TW": "顯示名稱（可空白）：",
        "zh-CN": "显示名称（可空白）：",
        "en": "Label (optional):",
        "ja": "表示名（空白可）：",
        "ko": "표시명 (공백 가능):",
        "es": "Etiqueta (opcional):",
    },
    "btn_ok": {
        "zh-TW": "加入",
        "zh-CN": "加入",
        "en": "Add",
        "ja": "追加",
        "ko": "추가",
        "es": "Agregar",
    },
    "theme_menu": {
        "zh-TW": "主題",
        "zh-CN": "主题",
        "en": "Theme",
        "ja": "テーマ",
        "ko": "테마",
        "es": "Tema",
    },
    "lang_menu": {
        "zh-TW": "語言",
        "zh-CN": "语言",
        "en": "Language",
        "ja": "言語",
        "ko": "언어",
        "es": "Idioma",
    },
    "err_no_wl": {
        "zh-TW": "請先選擇一個 Watchlist",
        "zh-CN": "请先选择一个 Watchlist",
        "en": "Please select a Watchlist",
        "ja": "Watchlist を選択してください",
        "ko": "관심종을 선택하세요",
        "es": "Selecciona una Watchlist primero",
    },
    "err_no_select": {
        "zh-TW": "請先在列表中點選一個項目",
        "zh-CN": "请先在列表中点选一个项目",
        "en": "Please select an item in the list",
        "ja": "リストから項目を選択してください",
        "ko": "목록에서 항목을 선택하세요",
        "es": "Selecciona un elemento en la lista",
    },
}
